# Generated by Django 3.0.10 on 2021-04-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210415_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_results',
            old_name='question',
            new_name='user_question',
        ),
        migrations.RenameField(
            model_name='user_results',
            old_name='results',
            new_name='user_results',
        ),
    ]
