# Generated by Django 3.1.6 on 2021-04-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210422_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
